# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Screen_waiter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(879, 630)
        MainWindow.setMaximumSize(QtCore.QSize(879, 649))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 881, 631))
        self.label_4.setStyleSheet("background-image: url(:/newPrefix/istockphoto-874402896-612x612.jpg);")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/newPrefix/istockphoto-874402896-612x612.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-1, -1, 881, 611))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(690, 470, 171, 151))
        self.label_5.setStyleSheet("background-image: url(:/newPrefix/Εικόνα1.gif);")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/newPrefix/Εικόνα1.gif"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(0, 90, 891, 20))
        self.line.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 110, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(0, 170, 891, 20))
        self.line_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setGeometry(QtCore.QRect(-10, 250, 891, 20))
        self.line_3.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(0, 190, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(0, 350, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(0, 270, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(0, 430, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(0, 510, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.line_4 = QtWidgets.QFrame(self.frame)
        self.line_4.setGeometry(QtCore.QRect(0, 330, 891, 20))
        self.line_4.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.frame)
        self.line_5.setGeometry(QtCore.QRect(0, 410, 891, 20))
        self.line_5.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_11 = QtWidgets.QFrame(self.frame)
        self.line_11.setGeometry(QtCore.QRect(0, 490, 891, 20))
        self.line_11.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.frame)
        self.line_12.setGeometry(QtCore.QRect(0, 570, 891, 20))
        self.line_12.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_13 = QtWidgets.QFrame(self.frame)
        self.line_13.setGeometry(QtCore.QRect(110, 0, 20, 581))
        self.line_13.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(130, 0, 181, 91))
        self.label_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.line_14 = QtWidgets.QFrame(self.frame)
        self.line_14.setGeometry(QtCore.QRect(310, 0, 20, 581))
        self.line_14.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(330, 0, 131, 91))
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.line_15 = QtWidgets.QFrame(self.frame)
        self.line_15.setGeometry(QtCore.QRect(460, 0, 20, 581))
        self.line_15.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(480, 0, 111, 91))
        self.label_10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.line_16 = QtWidgets.QFrame(self.frame)
        self.line_16.setGeometry(QtCore.QRect(590, 0, 20, 581))
        self.line_16.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.label_24 = QtWidgets.QLabel(self.frame)
        self.label_24.setGeometry(QtCore.QRect(610, 0, 141, 91))
        self.label_24.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_24.setObjectName("label_24")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.frame)
        self.verticalScrollBar.setGeometry(QtCore.QRect(860, 110, 20, 461))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.lcdNumber = QtWidgets.QLCDNumber(self.frame)
        self.lcdNumber.setGeometry(QtCore.QRect(200, 120, 61, 41))
        self.lcdNumber.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.frame)
        self.lcdNumber_2.setGeometry(QtCore.QRect(200, 200, 61, 41))
        self.lcdNumber_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.frame)
        self.lcdNumber_3.setGeometry(QtCore.QRect(200, 280, 61, 41))
        self.lcdNumber_3.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.lcdNumber_10 = QtWidgets.QLCDNumber(self.frame)
        self.lcdNumber_10.setGeometry(QtCore.QRect(200, 360, 61, 41))
        self.lcdNumber_10.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.lcdNumber_10.setObjectName("lcdNumber_10")
        self.lcdNumber_11 = QtWidgets.QLCDNumber(self.frame)
        self.lcdNumber_11.setGeometry(QtCore.QRect(200, 440, 61, 41))
        self.lcdNumber_11.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.lcdNumber_11.setObjectName("lcdNumber_11")
        self.lcdNumber_12 = QtWidgets.QLCDNumber(self.frame)
        self.lcdNumber_12.setGeometry(QtCore.QRect(200, 520, 61, 41))
        self.lcdNumber_12.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.lcdNumber_12.setObjectName("lcdNumber_12")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(330, 140, 121, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 220, 121, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(330, 300, 121, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(330, 380, 121, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(330, 460, 121, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setGeometry(QtCore.QRect(330, 540, 121, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.radioButton = QtWidgets.QRadioButton(self.frame)
        self.radioButton.setGeometry(QtCore.QRect(380, 110, 31, 31))
        self.radioButton.setStyleSheet("QRadioButton::indicator{\n"
"width: 50px;\n"
"heigth: 50px;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked{\n"
"background-color: rgb(0, 255, 0);\n"
"border: 2px solid black;\n"
"}\n"
"")
        self.radioButton.setText("")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_2.setGeometry(QtCore.QRect(380, 190, 31, 31))
        self.radioButton_2.setStyleSheet("QRadioButton::indicator{\n"
"width: 50px;\n"
"heigth: 50px;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked{\n"
"background-color: rgb(255, 0, 0);\n"
"border: 2px solid black;\n"
"}\n"
"")
        self.radioButton_2.setText("")
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_3.setGeometry(QtCore.QRect(380, 270, 31, 31))
        self.radioButton_3.setStyleSheet("QRadioButton::indicator{\n"
"width: 50px;\n"
"heigth: 50px;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked{\n"
"background-color: rgb(255, 0, 0);\n"
"border: 2px solid black;\n"
"}\n"
"")
        self.radioButton_3.setText("")
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_4.setGeometry(QtCore.QRect(380, 350, 31, 31))
        self.radioButton_4.setStyleSheet("QRadioButton::indicator{\n"
"width: 50px;\n"
"heigth: 50px;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked{\n"
"background-color: rgb(255, 0, 0);\n"
"border: 2px solid black;\n"
"}\n"
"")
        self.radioButton_4.setText("")
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_5.setGeometry(QtCore.QRect(380, 510, 31, 31))
        self.radioButton_5.setStyleSheet("QRadioButton::indicator{\n"
"width: 50px;\n"
"heigth: 50px;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked{\n"
"background-color: rgb(255, 0, 0);\n"
"border: 2px solid black;\n"
"}\n"
"")
        self.radioButton_5.setText("")
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_6.setGeometry(QtCore.QRect(380, 430, 31, 31))
        self.radioButton_6.setStyleSheet("QRadioButton::indicator{\n"
"width: 50px;\n"
"heigth: 50px;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked{\n"
"background-color: rgb(255, 0, 0);\n"
"border: 2px solid black;\n"
"}\n"
"")
        self.radioButton_6.setText("")
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_7 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_7.setGeometry(QtCore.QRect(490, 110, 31, 61))
        self.radioButton_7.setStyleSheet("QRadioButton::indicator{\n"
"width: 50px;\n"
"heigth: 50px;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked{\n"
"background-color: rgb(255, 0, 0);\n"
"border: 2px solid black;\n"
"}\n"
"")
        self.radioButton_7.setText("")
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_16 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_16.setGeometry(QtCore.QRect(490, 270, 31, 61))
        self.radioButton_16.setStyleSheet("QRadioButton::indicator{\n"
"width: 50px;\n"
"heigth: 50px;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked{\n"
"background-color: rgb(255, 0, 0);\n"
"border: 2px solid black;\n"
"}\n"
"")
        self.radioButton_16.setText("")
        self.radioButton_16.setObjectName("radioButton_16")
        self.radioButton_17 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_17.setGeometry(QtCore.QRect(490, 510, 31, 61))
        self.radioButton_17.setStyleSheet("QRadioButton::indicator{\n"
"width: 50px;\n"
"heigth: 50px;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked{\n"
"background-color: rgb(255, 0, 0);\n"
"border: 2px solid black;\n"
"}\n"
"")
        self.radioButton_17.setText("")
        self.radioButton_17.setObjectName("radioButton_17")
        self.radioButton_18 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_18.setGeometry(QtCore.QRect(490, 350, 31, 61))
        self.radioButton_18.setStyleSheet("QRadioButton::indicator{\n"
"width: 50px;\n"
"heigth: 50px;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked{\n"
"background-color: rgb(255, 0, 0);\n"
"border: 2px solid black;\n"
"}\n"
"")
        self.radioButton_18.setText("")
        self.radioButton_18.setObjectName("radioButton_18")
        self.radioButton_19 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_19.setGeometry(QtCore.QRect(490, 430, 31, 61))
        self.radioButton_19.setStyleSheet("QRadioButton::indicator{\n"
"width: 50px;\n"
"heigth: 50px;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked{\n"
"background-color: rgb(255, 0, 0);\n"
"border: 2px solid black;\n"
"}\n"
"")
        self.radioButton_19.setText("")
        self.radioButton_19.setObjectName("radioButton_19")
        self.radioButton_20 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_20.setGeometry(QtCore.QRect(630, 270, 31, 61))
        self.radioButton_20.setStyleSheet("QRadioButton::indicator{\n"
"width: 50px;\n"
"heigth: 50px;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked{\n"
"background-color: rgb(255, 0, 0);\n"
"border: 2px solid black;\n"
"}\n"
"")
        self.radioButton_20.setText("")
        self.radioButton_20.setObjectName("radioButton_20")
        self.radioButton_21 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_21.setGeometry(QtCore.QRect(630, 110, 31, 61))
        self.radioButton_21.setStyleSheet("QRadioButton::indicator{\n"
"width: 50px;\n"
"heigth: 50px;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked{\n"
"background-color: rgb(255, 0, 0);\n"
"border: 2px solid black;\n"
"}\n"
"")
        self.radioButton_21.setText("")
        self.radioButton_21.setObjectName("radioButton_21")
        self.radioButton_23 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_23.setGeometry(QtCore.QRect(630, 510, 31, 61))
        self.radioButton_23.setStyleSheet("QRadioButton::indicator{\n"
"width: 50px;\n"
"heigth: 50px;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked{\n"
"background-color: rgb(255, 0, 0);\n"
"border: 2px solid black;\n"
"}\n"
"")
        self.radioButton_23.setText("")
        self.radioButton_23.setObjectName("radioButton_23")
        self.radioButton_24 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_24.setGeometry(QtCore.QRect(630, 350, 31, 61))
        self.radioButton_24.setStyleSheet("QRadioButton::indicator{\n"
"width: 50px;\n"
"heigth: 50px;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked{\n"
"background-color: rgb(255, 0, 0);\n"
"border: 2px solid black;\n"
"}\n"
"")
        self.radioButton_24.setText("")
        self.radioButton_24.setObjectName("radioButton_24")
        self.radioButton_25 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_25.setGeometry(QtCore.QRect(630, 430, 31, 61))
        self.radioButton_25.setStyleSheet("QRadioButton::indicator{\n"
"width: 50px;\n"
"heigth: 50px;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked{\n"
"background-color: rgb(255, 0, 0);\n"
"border: 2px solid black;\n"
"}\n"
"")
        self.radioButton_25.setText("")
        self.radioButton_25.setObjectName("radioButton_25")
        self.line_23 = QtWidgets.QFrame(self.frame)
        self.line_23.setGeometry(QtCore.QRect(750, 0, 20, 581))
        self.line_23.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_23.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.label_22 = QtWidgets.QLabel(self.frame)
        self.label_22.setGeometry(QtCore.QRect(770, -10, 111, 101))
        self.label_22.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_22.setObjectName("label_22")
        self.pushButton_13 = QtWidgets.QPushButton(self.frame)
        self.pushButton_13.setGeometry(QtCore.QRect(800, 130, 41, 23))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.frame)
        self.pushButton_14.setGeometry(QtCore.QRect(800, 210, 41, 23))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.frame)
        self.pushButton_15.setGeometry(QtCore.QRect(800, 290, 41, 23))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.frame)
        self.pushButton_16.setGeometry(QtCore.QRect(800, 530, 41, 23))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.frame)
        self.pushButton_17.setGeometry(QtCore.QRect(800, 450, 41, 23))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.frame)
        self.pushButton_18.setGeometry(QtCore.QRect(800, 370, 41, 23))
        self.pushButton_18.setObjectName("pushButton_18")
        self.checkBox = QtWidgets.QCheckBox(self.frame)
        self.checkBox.setGeometry(QtCore.QRect(430, 110, 21, 31))
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_2.setGeometry(QtCore.QRect(430, 190, 21, 31))
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_3.setGeometry(QtCore.QRect(430, 270, 21, 31))
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_4.setGeometry(QtCore.QRect(430, 350, 21, 31))
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_6 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_6.setGeometry(QtCore.QRect(430, 510, 21, 31))
        self.checkBox_6.setText("")
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_5 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_5.setGeometry(QtCore.QRect(430, 430, 21, 31))
        self.checkBox_5.setText("")
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_13 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_13.setGeometry(QtCore.QRect(550, 120, 21, 41))
        self.checkBox_13.setText("")
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_14 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_14.setGeometry(QtCore.QRect(550, 200, 21, 41))
        self.checkBox_14.setText("")
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_15 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_15.setGeometry(QtCore.QRect(550, 280, 21, 41))
        self.checkBox_15.setText("")
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkBox_16 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_16.setGeometry(QtCore.QRect(550, 440, 21, 41))
        self.checkBox_16.setText("")
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_17 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_17.setGeometry(QtCore.QRect(550, 360, 21, 41))
        self.checkBox_17.setText("")
        self.checkBox_17.setObjectName("checkBox_17")
        self.checkBox_18 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_18.setGeometry(QtCore.QRect(550, 520, 21, 41))
        self.checkBox_18.setText("")
        self.checkBox_18.setObjectName("checkBox_18")
        self.checkBox_43 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_43.setGeometry(QtCore.QRect(690, 200, 21, 41))
        self.checkBox_43.setText("")
        self.checkBox_43.setObjectName("checkBox_43")
        self.checkBox_44 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_44.setGeometry(QtCore.QRect(690, 280, 21, 41))
        self.checkBox_44.setText("")
        self.checkBox_44.setObjectName("checkBox_44")
        self.checkBox_45 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_45.setGeometry(QtCore.QRect(690, 520, 21, 41))
        self.checkBox_45.setText("")
        self.checkBox_45.setObjectName("checkBox_45")
        self.checkBox_46 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_46.setGeometry(QtCore.QRect(690, 440, 21, 41))
        self.checkBox_46.setText("")
        self.checkBox_46.setObjectName("checkBox_46")
        self.checkBox_47 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_47.setGeometry(QtCore.QRect(690, 360, 21, 41))
        self.checkBox_47.setText("")
        self.checkBox_47.setObjectName("checkBox_47")
        self.checkBox_48 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_48.setGeometry(QtCore.QRect(690, 120, 21, 41))
        self.checkBox_48.setText("")
        self.checkBox_48.setObjectName("checkBox_48")
        self.radioButton_15 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_15.setGeometry(QtCore.QRect(490, 200, 31, 41))
        self.radioButton_15.setStyleSheet("QRadioButton::indicator{\n"
"width: 50px;\n"
"heigth: 50px;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked{\n"
"background-color: rgb(0, 255, 0);\n"
"border: 2px solid black;\n"
"}\n"
"")
        self.radioButton_15.setText("")
        self.radioButton_15.setObjectName("radioButton_15")
        self.radioButton_22 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_22.setGeometry(QtCore.QRect(630, 200, 31, 41))
        self.radioButton_22.setStyleSheet("QRadioButton::indicator{\n"
"width: 50px;\n"
"heigth: 50px;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked{\n"
"background-color: rgb(0, 255, 0);\n"
"border: 2px solid black;\n"
"}\n"
"")
        self.radioButton_22.setText("")
        self.radioButton_22.setObjectName("radioButton_22")
        self.checkBox_67 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_67.setGeometry(QtCore.QRect(280, 280, 21, 41))
        self.checkBox_67.setText("")
        self.checkBox_67.setObjectName("checkBox_67")
        self.checkBox_68 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_68.setGeometry(QtCore.QRect(280, 360, 21, 41))
        self.checkBox_68.setText("")
        self.checkBox_68.setObjectName("checkBox_68")
        self.checkBox_69 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_69.setGeometry(QtCore.QRect(280, 520, 21, 41))
        self.checkBox_69.setText("")
        self.checkBox_69.setObjectName("checkBox_69")
        self.checkBox_70 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_70.setGeometry(QtCore.QRect(280, 120, 21, 41))
        self.checkBox_70.setText("")
        self.checkBox_70.setObjectName("checkBox_70")
        self.checkBox_71 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_71.setGeometry(QtCore.QRect(280, 200, 21, 41))
        self.checkBox_71.setText("")
        self.checkBox_71.setObjectName("checkBox_71")
        self.checkBox_72 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_72.setGeometry(QtCore.QRect(280, 440, 21, 41))
        self.checkBox_72.setText("")
        self.checkBox_72.setObjectName("checkBox_72")
        self.checkBox.raise_()
        self.label_5.raise_()
        self.line.raise_()
        self.label.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_11.raise_()
        self.line_4.raise_()
        self.line_5.raise_()
        self.line_11.raise_()
        self.line_12.raise_()
        self.line_13.raise_()
        self.label_6.raise_()
        self.line_14.raise_()
        self.label_7.raise_()
        self.line_15.raise_()
        self.label_10.raise_()
        self.line_16.raise_()
        self.label_24.raise_()
        self.verticalScrollBar.raise_()
        self.lcdNumber.raise_()
        self.lcdNumber_2.raise_()
        self.lcdNumber_3.raise_()
        self.lcdNumber_10.raise_()
        self.lcdNumber_11.raise_()
        self.lcdNumber_12.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.radioButton.raise_()
        self.radioButton_2.raise_()
        self.radioButton_3.raise_()
        self.radioButton_4.raise_()
        self.radioButton_5.raise_()
        self.radioButton_6.raise_()
        self.radioButton_7.raise_()
        self.radioButton_16.raise_()
        self.radioButton_17.raise_()
        self.radioButton_18.raise_()
        self.radioButton_19.raise_()
        self.radioButton_20.raise_()
        self.radioButton_21.raise_()
        self.radioButton_23.raise_()
        self.radioButton_24.raise_()
        self.radioButton_25.raise_()
        self.line_23.raise_()
        self.label_22.raise_()
        self.pushButton_13.raise_()
        self.pushButton_14.raise_()
        self.pushButton_15.raise_()
        self.pushButton_16.raise_()
        self.pushButton_17.raise_()
        self.pushButton_18.raise_()
        self.checkBox_2.raise_()
        self.checkBox_3.raise_()
        self.checkBox_4.raise_()
        self.checkBox_6.raise_()
        self.checkBox_5.raise_()
        self.checkBox_13.raise_()
        self.checkBox_14.raise_()
        self.checkBox_15.raise_()
        self.checkBox_16.raise_()
        self.checkBox_17.raise_()
        self.checkBox_18.raise_()
        self.checkBox_43.raise_()
        self.checkBox_44.raise_()
        self.checkBox_45.raise_()
        self.checkBox_46.raise_()
        self.checkBox_47.raise_()
        self.checkBox_48.raise_()
        self.radioButton_15.raise_()
        self.radioButton_22.raise_()
        self.checkBox_67.raise_()
        self.checkBox_68.raise_()
        self.checkBox_69.raise_()
        self.checkBox_70.raise_()
        self.checkBox_71.raise_()
        self.checkBox_72.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 879, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ΤΡΑΠΕΖΙ 1"))
        self.label_2.setText(_translate("MainWindow", "ΤΡΑΠΕΖΙ 2"))
        self.label_3.setText(_translate("MainWindow", "ΤΡΑΠΕΖΙ 4"))
        self.label_8.setText(_translate("MainWindow", "ΤΡΑΠΕΖΙ 3"))
        self.label_9.setText(_translate("MainWindow", "ΤΡΑΠΕΖΙ 5"))
        self.label_11.setText(_translate("MainWindow", "ΤΡΑΠΕΖΙ 6"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">ΑΡΙΘΜΟΣ </span></p><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">ΠΙΣΤΟΠΟΙΗΤΙΚΩΝ</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">ΕΚΚΡΕΜΕΙ</span></p><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">ΠΑΡΑΓΓΕΛΙΑ</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">ΠΛΗΡΩΜΗ</span></p></body></html>"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">ΒΟΗΘΕΙΑ </span></p><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">ΣΕΡΒΙΤΟΡΟΥ</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Δες την παραγγελια"))
        self.pushButton_2.setText(_translate("MainWindow", "Δες την παραγγελια"))
        self.pushButton_3.setText(_translate("MainWindow", "Δες την παραγγελια"))
        self.pushButton_4.setText(_translate("MainWindow", "Δες την παραγγελια"))
        self.pushButton_5.setText(_translate("MainWindow", "Δες την παραγγελια"))
        self.pushButton_6.setText(_translate("MainWindow", "Δες την παραγγελια"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p><p align=\"center\"><br/><span style=\" font-size:14pt; font-weight:600;\">RESET</span></p><p align=\"center\"><br/></p><p align=\"center\"><br/></p></body></html>"))
        self.pushButton_13.setText(_translate("MainWindow", "OK"))
        self.pushButton_14.setText(_translate("MainWindow", "OK"))
        self.pushButton_15.setText(_translate("MainWindow", "OK"))
        self.pushButton_16.setText(_translate("MainWindow", "OK"))
        self.pushButton_17.setText(_translate("MainWindow", "OK"))
        self.pushButton_18.setText(_translate("MainWindow", "OK"))
import rr_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
